title: Data science in a rabbit hole
description: A journey of a grad student who wants to find his way out into the world of puzzling people
show_downloads: false
google_analytics:
theme: 
markdown: kramdown
excerpt_separator: <!--more-->

# Syntax highlighting
highlighter: rouge
